# Generated by Django 3.2 on 2024-03-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typewordsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
