# Generated by Django 4.2.5 on 2024-03-27 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typewordsapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='WordList',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
