# Generated by Django 4.2.5 on 2024-03-27 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typewordsapp', '0003_rename_list_wordlist_alter_lesson_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words_Translations',
            new_name='Word',
        ),
        migrations.RenameField(
            model_name='wordlist',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='wordlist',
            old_name='name',
            new_name='list_name',
        ),
    ]
