# Generated by Django 4.2.5 on 2024-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typewordsapp', '0004_rename_words_translations_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='user',
            new_name='creted_by',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='list',
            new_name='word_list_id',
        ),
    ]
