# Generated by Django 4.2.5 on 2024-03-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typewordsapp', '0005_rename_user_word_creted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='num_of_lesson',
            new_name='lesson_number',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='word_translation',
            new_name='word_id',
        ),
    ]
