# Generated by Django 4.2.5 on 2024-03-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typewordsapp', '0006_rename_user_lesson_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
