# Generated by Django 4.2.5 on 2024-03-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typewordsapp', '0007_rename_creted_by_word_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='times_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='times_correct',
            field=models.IntegerField(default=0),
        ),
    ]
