# Generated by Django 4.2.5 on 2024-03-30 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typewordsapp', '0008_word_times_asked_word_times_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typewordsapp.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typewordsapp.wordlist'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
